name: skyline2isocor
owner: workflow4metabolomics
description: Preparing skyline output data for use in IsoCor software for natural abundance isotope correction.
categories: [Metabolomics]
homepage_url: https://github.com/MetaboHUB-MetaToul-FluxoMet/Skyline2IsoCor